name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Разрешает ручной запуск из вкладки Actions

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: artem-sedykh/buildozer-action@v1
        with:
          buildozer_version: stable
          workdir: '.'
          buildozer_params: '-v'

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: OblivionReaper-APK
          path: ./*.apk
          retention-days: 7
